server:
  port: 7002

spring:
  application:
    name: eureka-provider1

spring.cloud.client.ip-address: 192.168.151.175

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://server1:7000/eureka/,http://server2:7001/eureka/
  instance:
    hostname: localhost